### ISSUE TITLE
Errors at test/index.html

### ISSUE THREAD

**Issue by guest271314** [jscodec/jswebm#8]
```
Uncaught TypeError: Class constructors may only return object or undefined
    at JsWebm.load (jswebm.js:477)
    at JsWebm.demux (jswebm.js:351)
    at runTest (test.js:30)
    at XMLHttpRequest.fileRequest.onload (test.js:17)
```

**Comment by brianxautumn** [comment]
Did you download the submodules?

**Comment by guest271314** [comment]
@brianxautumn To reproduce, download this repository as `.zip` folder, open "/jswebm-master/test/index.html" at `file:` protocol.

**Comment by brianxautumn** [comment]
Its because you didn't download the submodules for the test files. Clone it instead, then do 
`git submodule init` and
`git submodule update`. I could add a descriptive error for when it fails to get data

**Comment by brianxautumn** [comment]
Also that test file needs to be served from an http server, it won't work if you just click it.

**Comment by guest271314** [comment]
Have you considered including usage details and examples at README? 

Why is a server necessary?

**Comment by guest271314** [comment]
Unfortunately do not have enough disk space to download the entire https://github.com/Matroska-Org/matroska-test-files/tree/afa4b7fca0afcb988fdfe92103a030a416aefa16/test_files directory. Can a different `.mkv` file be used to test jswebm? 

Is the associated `.xml` file necessary before proceeding with testing?

**Comment by guest271314** [comment]
Was able clone repository and download `test1.mkv` and `test1-tag.xml`, still getting error.

**Comment by brianxautumn** [comment]
The server is necessary because of the cross origin request if it is being served as file:, I can include a dev server in the sample if you like

**Comment by guest271314** [comment]
@brianxautumn At Chromium we can use `--allow-file-access-from-files` to make the request at `file:` protocol from local filesystem. That portion of testing should not be an issue.

Trying to learn the fundamentals of creating a `.webm` file from scratch.Specifically for the ability to get raw image data and audio data from multiple media fragments and concatenate the data into a single `.webm` or `.mkv` file. 

Tried using `mkvmerge` at command line though am still unsuccessful, perhaps due to different codecs being used, no cues or different original video resolutions, though not entirely sure at this point.

**Comment by guest271314** [comment]
If a dev server is necessary, then yes, that would be helpful. What would really be helpful, though may be beyond the scope of this repository, is to describe the step by step details and procedure required for creating a `.webm` file from scratch using JavaScript, where the original input is, for example, `ImageData` and `AudioData` or `ArrayBuffer`s.

**Comment by guest271314** [comment]
FWIW, This is where am at at this point https://github.com/guest271314/MediaFragmentRecorder, https://github.com/whatwg/html/issues/3593#event-1542672549.

**Comment by brianxautumn** [comment]
Okay threw together a super fast demo. Check the main branch. I'll update the full readme this week. If  it is of use to you, I can add in functions. Also be sure to use webm, it doesn't support all mkv elements  yet. I'll list in the readme later which are supported.

**Comment by guest271314** [comment]
Still getting errors. 

```
customFileExample.js:16 ArrayBuffer(222978) {}
ogv-demuxer-webm.js:280  JSWEBM DEMUXER LOADED
ogv-demuxer-webm.js:2446 track data element not found, skipping : 63c5
load @ ogv-demuxer-webm.js:2446
load @ ogv-demuxer-webm.js:2182
load @ ogv-demuxer-webm.js:551
process @ ogv-demuxer-webm.js:471
demuxer.receiveInput @ customFileExample.js:8
receiveInput @ ogv-demuxer-webm.js:106
runTest @ customFileExample.js:7
fileRequest.onload @ customFileExample.js:18
XMLHttpRequest.send (async)
(anonymous) @ customFileExample.js:22
ogv-demuxer-webm.js:2446 track data element not found, skipping : 22b59c40
load @ ogv-demuxer-webm.js:2446
load @ ogv-demuxer-webm.js:2182
load @ ogv-demuxer-webm.js:551
process @ ogv-demuxer-webm.js:471
demuxer.receiveInput @ customFileExample.js:8
receiveInput @ ogv-demuxer-webm.js:106
runTest @ customFileExample.js:7
fileRequest.onload @ customFileExample.js:18
XMLHttpRequest.send (async)
(anonymous) @ customFileExample.js:22
ogv-demuxer-webm.js:2446 track data element not found, skipping : 565f
load @ ogv-demuxer-webm.js:2446
load @ ogv-demuxer-webm.js:2182
load @ ogv-demuxer-webm.js:551
process @ ogv-demuxer-webm.js:471
demuxer.receiveInput @ customFileExample.js:8
receiveInput @ ogv-demuxer-webm.js:106
runTest @ customFileExample.js:7
fileRequest.onload @ customFileExample.js:18
XMLHttpRequest.send (async)
(anonymous) @ customFileExample.js:22
ogv-demuxer-webm.js:2446 track data element not found, skipping : 382586
load @ ogv-demuxer-webm.js:2446
load @ ogv-demuxer-webm.js:2182
load @ ogv-demuxer-webm.js:551
process @ ogv-demuxer-webm.js:471
demuxer.receiveInput @ customFileExample.js:8
receiveInput @ ogv-demuxer-webm.js:106
runTest @ customFileExample.js:7
fileRequest.onload @ customFileExample.js:18
XMLHttpRequest.send (async)
(anonymous) @ customFileExample.js:22
ogv-demuxer-webm.js:2446 track data element not found, skipping : 4003
load @ ogv-demuxer-webm.js:2446
load @ ogv-demuxer-webm.js:2182
load @ ogv-demuxer-webm.js:551
process @ ogv-demuxer-webm.js:471
demuxer.receiveInput @ customFileExample.js:8
receiveInput @ ogv-demuxer-webm.js:106
runTest @ customFileExample.js:7
fileRequest.onload @ customFileExample.js:18
XMLHttpRequest.send (async)
(anonymous) @ customFileExample.js:22
ogv-demuxer-webm.js:2446 track data element not found, skipping : 388381
load @ ogv-demuxer-webm.js:2446
load @ ogv-demuxer-webm.js:2182
load @ ogv-demuxer-webm.js:551
process @ ogv-demuxer-webm.js:471
demuxer.receiveInput @ customFileExample.js:8
receiveInput @ ogv-demuxer-webm.js:106
runTest @ customFileExample.js:7
fileRequest.onload @ customFileExample.js:18
XMLHttpRequest.send (async)
(anonymous) @ customFileExample.js:22
ogv-demuxer-webm.js:2446 track data element not found, skipping : 81
load @ ogv-demuxer-webm.js:2446
load @ ogv-demuxer-webm.js:2182
load @ ogv-demuxer-webm.js:551
process @ ogv-demuxer-webm.js:471
demuxer.receiveInput @ customFileExample.js:8
receiveInput @ ogv-demuxer-webm.js:106
runTest @ customFileExample.js:7
fileRequest.onload @ customFileExample.js:18
XMLHttpRequest.send (async)
(anonymous) @ customFileExample.js:22
ogv-demuxer-webm.js:2458 Uncaught TypeError: Cannot read property 'loadMeta' of null
    at TrackLoader.getTrackEntry (ogv-demuxer-webm.js:2458)
    at Tracks.load (ogv-demuxer-webm.js:2186)
    at OGVDemuxerWebM.load (ogv-demuxer-webm.js:551)
    at OGVDemuxerWebM.process (ogv-demuxer-webm.js:471)
    at demuxer.receiveInput (customFileExample.js:8)
    at OGVDemuxerWebM.receiveInput (ogv-demuxer-webm.js:106)
    at runTest (customFileExample.js:7)
    at XMLHttpRequest.fileRequest.onload (customFileExample.js:18)
```

Yes, descriptions of functions available would be useful.

**Comment by brianxautumn** [comment]
Ah, it looks like there are a few elements that are not yet implemented that are in the matroska spec. Would it be possible to provide the file you are demuxing?

**Comment by brianxautumn** [comment]
Did a small update so that the stock demo demuxes test1.mkv.
I committed the built demo too, so just start `node test/example.js` and navigate to localhost:8080

**Comment by guest271314** [comment]
The file was a the generated "clock.webm" at blob:http://antimatter15.com/e0b11673-805a-4797-a39d-aa3e3ff3f1f4 linked to from https://github.com/antimatter15/whammy

**Comment by guest271314** [comment]
The file was a the generated "clock.webm" at http://antimatter15.com/whammy/clock.html linked to from https://github.com/antimatter15/whammy

**Comment by brianxautumn** [comment]
Try the demo one more time. It had an invalid element that it wasn't skipping correctly.

**Comment by guest271314** [comment]
No errors logged at `console`.

**Comment by guest271314** [comment]
What is the content of the `DataView` object `segmentInfo.dataInterface.currentBuffer`?

**Comment by brianxautumn** [comment]
Data view is an object that encapsulates the binary data. The data is read from here. I’m cleaning up the api and hope to have it documented in the next couple of days.
